export const LOAD_SHELTERS = 'LOAD_SHELTERS';
export const CHOOSE_SHELTER = 'CHOOSE_SHELTER';
export const UPDATE_AMOUNT = 'UPDATE_AMOUNT';
export const UPDATE_OPTION = 'UPDATE_OPTION';
export const PAGE_BACK = 'PAGE_BACK';
export const PAGE_FORWARD = 'PAGE_FORWARD';